config/routes.rb


Rails.application.routes.draw do
  namespace :hrms do
    resources :positions
  end
  resources :libraries
  resources :categories
  resources :permissions
  resources :post_comments
  resources :roles
  resources :posts

  #Devise Users
  devise_for :admins
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  draw :backend
  draw :hrms

  draw :dashboard
  draw :profile

  draw :api_v1

  scope "(:locale)", :locale => /en|mn/ do
    root to: "pages#index"
    get "page/index"
  end

  root to: "pages#index"

  #404
#  get '*unmatched_route', to: 'pages#route_not_found'
  #, only: [:show, :edit, :update, :preferences]
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :category
end

app/controllers/libraries_controller.rb
class LibrariesController < AdminController
  before_action :set_library, only: [:show, :edit, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:name, :slug, :description, :is_active)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.haml
= form_for @library do |f|
  - if @library.errors.any?
    #error_explanation
      %h2= "#{pluralize(@library.errors.count, "error")} prohibited this library from being saved:"
      %ul
        - @library.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :is_active
    = f.check_box :is_active
  .actions
    = f.submit 'Save'

app/views/libraries/edit.html.haml
%h1 Editing library

= render 'form'

= link_to 'Show', @library
\|
= link_to 'Back', libraries_path

app/views/libraries/index.html.haml

.justify-content-center
  .col-12.col-lg-10.col-xl-8
    %h1 Listing libraries

    %table
      %thead
        %tr
          %th Name
          %th Slug
          %th Description
          %th Is active
          %th
          %th
          %th

      %tbody
        - @libraries.each do |library|
          %tr
            %td= library.name
            %td= library.slug
            %td= library.description
            %td= library.is_active
            %td= link_to 'Show', library
            %td= link_to 'Edit', edit_library_path(library)
            %td= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' }

    = link_to 'New Library', new_library_path

app/views/libraries/new.html.haml
%h1 New library

= render 'form'

= link_to 'Back', libraries_path

app/views/libraries/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @library.name
%p
  %b Slug:
  = @library.slug
%p
  %b Description:
  = @library.description
%p
  %b Is active:
  = @library.is_active

= link_to 'Edit', edit_library_path(@library)
\|
= link_to 'Back', libraries_path