config/routes.rb


Rails.application.routes.draw do
  namespace :hrms do
    resources :positions
  end
  resources :libraries
  resources :categories
  resources :permissions
  resources :post_comments
  resources :roles
  resources :posts

  #Devise Users
  devise_for :admins
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  draw :backend
  draw :hrms

  draw :dashboard
  draw :profile

  draw :api_v1

  scope "(:locale)", :locale => /en|mn/ do
    root to: "pages#index"
    get "page/index"
  end

  root to: "pages#index"

  #404
#  get '*unmatched_route', to: 'pages#route_not_found'
  #, only: [:show, :edit, :update, :preferences]
end

app/models/hrms.rb
module Hrms
  def self.table_name_prefix
    'hrms_'
  end
end

app/models/hrms/department.rb
class Hrms::Department < ApplicationRecord
  has_many :position

  validates :name, presence: true
end

app/models/hrms/position.rb
class Hrms::Position < ApplicationRecord
  belongs_to :department

  validates :name, presence: true
end

app/controllers/dashboard/hrms_controller.rb
class Dashboard::HrmsController < AdminController

  layout "hrms"

  def index

  end
end

app/controllers/hrms/departments_controller.rb
class Hrms::DepartmentsController < Backend::PreferenceController
  before_action :set_hrms_department, only: [:show, :edit, :update, :destroy]

  # GET /hrms/departments
  # GET /hrms/departments.json
  def index
    @hrms_departments = Hrms::Department.all
  end

  # GET /hrms/departments/1
  # GET /hrms/departments/1.json
  def show
  end

  # GET /hrms/departments/new
  def new
    @hrms_department = Hrms::Department.new
  end

  # GET /hrms/departments/1/edit
  def edit
  end

  # POST /hrms/departments
  # POST /hrms/departments.json
  def create
    @hrms_department = Hrms::Department.new(hrms_department_params)

    respond_to do |format|
      if @hrms_department.save
        format.html { redirect_to @hrms_department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @hrms_department }
      else
        format.html { render :new }
        format.json { render json: @hrms_department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hrms/departments/1
  # PATCH/PUT /hrms/departments/1.json
  def update
    respond_to do |format|
      if @hrms_department.update(hrms_department_params)
        format.html { redirect_to @hrms_department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @hrms_department }
      else
        format.html { render :edit }
        format.json { render json: @hrms_department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hrms/departments/1
  # DELETE /hrms/departments/1.json
  def destroy
    @hrms_department.destroy
    respond_to do |format|
      format.html { redirect_to hrms_departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hrms_department
      @hrms_department = Hrms::Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hrms_department_params
      params.require(:hrms_department).permit(:name, :description, :leave_allow_count, :max_ppl_absent, :max_absent_length)
    end
end

app/controllers/hrms/positions_controller.rb
class Hrms::PositionsController < AdminController
  before_action :set_hrms_position, only: [:show, :edit, :update, :destroy]

  layout "hrms"

  # GET /hrms/positions
  # GET /hrms/positions.json
  def index
    @hrms_positions = Hrms::Position.all
  end

  # GET /hrms/positions/1
  # GET /hrms/positions/1.json
  def show
  end

  # GET /hrms/positions/new
  def new
    @hrms_position = Hrms::Position.new
  end

  # GET /hrms/positions/1/edit
  def edit
  end

  # POST /hrms/positions
  # POST /hrms/positions.json
  def create
    @hrms_position = Hrms::Position.new(hrms_position_params)

    respond_to do |format|
      if @hrms_position.save
        format.html { redirect_to @hrms_position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @hrms_position }
      else
        format.html { render :new }
        format.json { render json: @hrms_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hrms/positions/1
  # PATCH/PUT /hrms/positions/1.json
  def update
    respond_to do |format|
      if @hrms_position.update(hrms_position_params)
        format.html { redirect_to @hrms_position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @hrms_position }
      else
        format.html { render :edit }
        format.json { render json: @hrms_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hrms/positions/1
  # DELETE /hrms/positions/1.json
  def destroy
    @hrms_position.destroy
    respond_to do |format|
      format.html { redirect_to hrms_positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hrms_position
      @hrms_position = Hrms::Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hrms_position_params
      params.require(:hrms_position).permit(:name, :description, :department_id)
    end
end

app/helpers/dashboard/hrms_helper.rb
module Dashboard::HrmsHelper
end

app/helpers/hrms/departments_helper.rb
module Hrms::DepartmentsHelper
end

app/helpers/hrms/positions_helper.rb
module Hrms::PositionsHelper
end

app/views/hrms/positions/_form.html.erb
<%= form_for @hrms_position do |f| %>
  <% if @hrms_position.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@hrms_position.errors.count, "error")} prohibited this hrms_position from being saved:" %>
      </h2>
      <ul>
        <% @hrms_position.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :department_id %>
    <%= collection_select(:hrms_position, :department_id, Hrms::Department.all, :id, :name, prompt: true, class:'custom-select d-block w-100') %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/hrms/positions/_form.html.haml
= form_for @hrms_position do |f|
  - if @hrms_position.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hrms_position.errors.count, "error")} prohibited this hrms_position from being saved:"
      %ul
        - @hrms_position.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :department_id
    = collection_select(:hrms_position, :department_id, Hrms::Department.all, :id, :name, prompt: true, :class=>'select')
  .actions
    = f.submit 'Save'

app/views/hrms/positions/edit.html.haml
%h1 Editing hrms_position

= render 'form'

= link_to 'Show', @hrms_position
\|
= link_to 'Back', hrms_positions_path

app/views/hrms/positions/index.html.haml
.row.justify-content-center{:style => "margin-top:10px;"}
  .col-12.col-lg-10.col-xl-8
    %p#notice= notice
    #hrms_positions.card
      .card-header
        / Title
        .row.align-items-center
          .col
            / Title
            %h4.card-header-title
              Positions
          .col-auto
            .input-group.input-group-sm.input-group-merge
              %input.form-control.form-control-prepended.search{:placeholder => "Search", :type => "text"}/
              .input-group-prepend
                .input-group-text
                  %span.fe.fe-search
          .col-auto
            / Button
            = link_to 'New Position', new_hrms_position_path, class: "btn btn-sm btn-white"
      - if @hrms_positions.size > 0
        .table-responsive.mb-0
          %table.table.table-sm.table-nowrap.card-table
            %thead
              %tr
                %th Name
                %th Description
                %th Department
                %th
                %th
                %th

            %tbody.list
              - @hrms_positions.each do |hrms_position|
                %tr
                  %td= hrms_position.name
                  %td= hrms_position.description
                  %td= hrms_position.department.name
                  %td= link_to 'Show', hrms_position
                  %td= link_to 'Edit', edit_hrms_position_path(hrms_position)
                  %td= link_to 'Destroy', hrms_position, method: :delete, data: { confirm: 'Are you sure?' }
      - else
        .card.card-inactive{:style => "margin-bottom: 0px;"}
          .card-body.text-center
            / Image
            %img.img-fluid{:alt => "...", :src => "/assets/img/illustrations/scale.svg", :style => "max-width: 182px;"}/
            / Title
            %h1
              No Positions
            / Subtitle
            %p.text-muted
              Create a first location
            / Button
            = link_to 'New Position', new_hrms_position_path, class: "btn btn-primary"

app/views/hrms/positions/new.html.haml
%h1 New hrms_position

= render 'form'

= link_to 'Back', hrms_positions_path

app/views/hrms/positions/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @hrms_position.name
%p
  %b Description:
  = @hrms_position.description

= link_to 'Edit', edit_hrms_position_path(@hrms_position)
\|
= link_to 'Back', hrms_positions_path